---

- name: 'Test service_facts'
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - service_facts:
    - set_fact:
        running_services_A: "{{ ansible_facts.services|dict2items|
                 json_query('[?value.state == `running`].key') }}"
    - debug:
        var: running_services_A

# Is there a way to compare different variables with json?
# https://stackoverflow.com/questions/57995250/is-there-a-way-to-compare-different-variables-with-json
