- hosts: localhost
  gather_facts: no
  vars:
    fruits: ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']

  tasks:
    - debug:
        var: fruits
    - debug:
        msg: "{{ fruits|append('tangerine') }}"
