---

- hosts: localhost
  gather_facts: no
  vars:
    input: [ "a", "b", "c" ]
  tasks:
    - debug:
        msg: "{{ 'abc'|string_postfix('-Z') }}"
    - set_fact:
        output: "{{ input|map('string_postfix', '-Z')|list }}"
    - debug:
        var: output
    - debug:
        msg: "{{ lookup('file', 'test.txt')|string_count('phrase') }}"
    - debug:
        msg: "{{ lookup('file', 'test.txt')|string_find('phrase') }}"
