- hosts: localhost
  gather_facts: no
  tasks:
    - lineinfile:
        path: "{{ playbook_dir }}/test10.txt"
        insertafter: '[tag1]'
        # firstmatch: yes
        # insertbefore: '[tag2]'
        line: "{{ item }}"
      loop:
        - '# This is line 1'

# How to add lines after pattern by ansible playbook
# https://stackoverflow.com/questions/57125421/how-to-add-lines-after-pattern-by-ansible-playbook
