- hosts: localhost
  gather_facts: no

  tasks:
    - lineinfile:
        path: '<PATH>'
        regexp: '<REGEX>'
        line: '<REPLACE'
      check_mode: true
      notify: run handler1

    - lineinfile:
        path: "<PATH>"
        regexp: '<REGEX>'
        line: '<REPLACE'

  handlers:
    
    - name: run handler1
      debug:
        msg: handler1 running ...

# Ansible predict if entry will change before commiting it
# https://stackoverflow.com/questions/57930646/ansible-predict-if-entry-will-change-before-commiting-it/

