- hosts: localhost
  gather_facts: no

  tasks:
    - lineinfile:
        path: '/scratch/tmp/test-play-10.txt'
        regexp: 'AAAAA'
        line: 'BBBBB'
      check_mode: true
      notify: run handler1
      tags: t1

    - lineinfile:
        path: "/scratch/tmp/test-play-10.txt"
        regexp: 'AAAAA'
        line: 'BBBBB'
      tags: t2

  handlers:
    - name: run handler1
      debug:
        msg: Action because the line will change.
      tags: t1

# Ansible predict if entry will change before commiting it
# https://stackoverflow.com/questions/57930646/ansible-predict-if-entry-will-change-before-commiting-it/
