---
- hosts: localhost
  gather_facts: false
  tasks:
    - replace:
        path: test2.txt
        regexp: "<sadmin>((?:[A-Z]+\n)+)</sadmin>"
        replace: |-
          <sadmin>
            <user>user1@somedomain</user>
            <user>user2@somedomain</user>
            <user>user3@somedomain</user>
          </sadmin>
