---

- hosts: '{{ var_hosts }}'
  gather_facts: no
  tasks:
    - debug:
        var: inventory_hostname
    - debug:
        msg: "{{ 'group2' | regex_search('^group*') }}"
    - debug:
        var: var_hosts
    - debug:
        msg: "{{ 'group2' | regex_search(var_hosts) }}"

# How to patterns to specify multiple groups to run against
# https://stackoverflow.com/questions/56068650/how-to-patterns-to-specify-multiple-groups-to-run-against/

# EOF
...
