- hosts: localhost
  gather_facts: no
  vars_files:
    - vars-1.json
  vars:
    host_collection: hci
  tasks:
    - debug: var=results|json_query('[?name==`hc1`].id')
    - debug: var=results|json_query('[?name==`{{ host_collection }}`].id')
    - debug: var="{{ results|json_query('[?name==`' ~ host_collection ~ '`].id') }}"
